version: '3.8'
name: bik-web-response
services:
  backend:
    build: ./backend
    ports:
      - "1913:1913"
      - "1914:1914"
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "1912:1912"
    networks:
      - app-network
    stdin_open: true
    tty: true
    depends_on:
      - backend
networks:
      app-network:
        driver: bridge
volumes:
  data:
  logs: