version: '3.8'
name: bik-web-response
services:
  backend:
    build: ./backend
    ports:
      - "1913:1913"
      - "1914:1914"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "1912:1912"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app-network
    stdin_open: true
    tty: true
    depends_on:
      - backend
networks:
      app-network:
        driver: bridge
volumes:
  data:
  logs: