on:
  push:
    branches: [ github-actions-setup ]
  pull_request:
    branches: [ main ]
# env:
#   DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
#   DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Build docker images
      #   run: docker-compose up -d
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Image
        run: |
          docker images
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y4o7w7w7
          # aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y4o7w7w7
          # docker tag bik-web-response_frontend 231285429685.dkr.ecr.us-east-2.amazonaws.com/bik-web-response-docker-images:frontend
          # docker tag bik-web-response_backend 231285429685.dkr.ecr.us-east-2.amazonaws.com/bik-web-response-docker-images:backend
          # docker push 231285429685.dkr.ecr.us-east-2.amazonaws.com/bik-web-response-docker-images:frontend
          # docker push 231285429685.dkr.ecr.us-east-2.amazonaws.com/bik-web-response-docker-images:backend