on:
  push:
    branches: [ docker-and-build-change ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Backend linting
        working-directory: ./backend
        run: |
          npx eslint
          npx prettier -c .
      - name: Frontend linting
        run: |
          cd frontend/
          npx eslint .
          npx prettier -c .
          cd
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: docker-compose up -d
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y4o7w7w7
          docker tag bik-web-response_backend public.ecr.aws/y4o7w7w7/bik-web-response:backend
          docker tag bik-web-response_frontend public.ecr.aws/y4o7w7w7/bik-web-response:frontend
          docker push public.ecr.aws/y4o7w7w7/bik-web-response:backend
          docker push public.ecr.aws/y4o7w7w7/bik-web-response:frontend